### ISSUE TITLE
mixed types in columns?

### ISSUE THREAD

**Issue by matt-long** [NCAR/intake-esm#15]
Should we be setting a default type in `DataFrame` columns?

**Comment by andersy005** [comment]
@matt-long, is this still an issue?

**Comment by andersy005** [comment]
@matt-long, 

While working on #66, I realized that this issue causes a lot of other issues when it comes to the `.search()` method (when the default value for a column is not compatible with the column data type). For example, if the column is supposed to contain integers, and pandas encounters `None`, the column data type is cast to `float`. 
As a result, the `search()` method becomes unreliable. 

> Should we be setting a default type in DataFrame columns?

This sounds like a step in the right direction though It may not be an easy task as the number of collections supported in intake-esm increases. 

- Can we replace `.csv` with a different file format such as `parquet` or `hdf5` that maintains the original column data types instead of infering them at runtime? 
- One disadvantage of these formats is that they are not human-readable. Would this be a problem to the users?

**Comment by matt-long** [comment]
I don't see a problem with non-human-readable formats.
