### ISSUE TITLE
Missing `config` module?

### ISSUE THREAD

**Issue by jbusecke** [NCAR/intake-esm#203]
I was trying to silence the read in progress as described in #75 

```
from intake_esm import config
config.set({'progress-bar': False})

```
and I am getting the following error.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-59362f4880f4> in <module>
      2 # intake_esm.__version__
      3 
----> 4 from intake_esm import config

ImportError: cannot import name 'config' from 'intake_esm' (/srv/conda/envs/notebook/lib/python3.7/site-packages/intake_esm/__init__.py)
```
and it seems the module has moved?

```
import intake_esm
intake_esm.__version__
```

`'2019.12.13.post26'`

**Comment by andersy005** [comment]
@jbusecke, the config module was deprecated when we refactored intake-esm (since `v2019.10`)

Today, you can pass `progressbar=False` when opening the json 

```python
col = intake.open_esm_datastore(col_url, progressbar=False)
```

https://github.com/NCAR/intake-esm/blob/525f02fad4b73a5df2947550f0ed3d66babaee93/intake_esm/core.py#L69

In case what you want is to disable the progress on a line by line basis (instead of having to pass it to `open_esm_datastore()`--See example below--, let me know and we will support that option too :


```python

col = intake.open_esm_datastore(col_url)

with config.set({'progress-bar': False}):
  # Do something with the progress bar off
  .....


# Do more stuff with the progress bar on
.....
```

**Comment by jbusecke** [comment]
Thanks @andersy005, Ill play around with the existing option and see if that works for my purposes.

**Comment by andersy005** [comment]
You are welcome! Is it okay to close this?

**Comment by jbusecke** [comment]
Yes absolutely. Ill go ahead and close
