### ISSUE TITLE
CMIP6 version of cmip.py

### ISSUE THREAD

**Issue by naomi-henderson** [NCAR/intake-esm#43]
Thanks @andersy005 for your helpful additions to esgf2xarray !   I am also interested in combining `esgf_search` of `esgf2xarray` and `open_esm_metadatastore` of `intake-esm` similar to your description of discussion with @matt-long in  https://github.com/pangeo-data/esgf2xarray/issues/1#issuecomment-470763581.  In my case I would also like to be able to compare a esgf dataframe with a intake-esm dataframe to keep track of the new CMIP6 data as it appears on ESGF to trigger the download of any data of interest to our local machines.

So ...  I am hoping to configure the intake_esm cmip functionality to work with the new directory structure of the CMIP6 archive.  ESGF changed the directory structure and made other important changes - there is no longer an entity called "realm" in the path and "table_id" specifies both realm and frequency.  There is an important new "grid_label"  and we probably need to keep track of some additional information (checksums?).   

Before I dive in and make a new version of [cmip.py](https://github.com/NCAR/intake-esm/blob/master/intake_esm/cmip.py) and add a 'cmip6' collection to [config.yaml](https://github.com/NCAR/intake-esm/blob/master/intake_esm/config.yaml),  I thought I would check and see if anyone else is working on this?

**Comment by matt-long** [comment]
@naomi-henderson I think you can go ahead and work on this. @andersy005, please chime in if you feel otherwise.

I think we can improve the generality in [cmip.py](https://github.com/NCAR/intake-esm/blob/master/intake_esm/cmip.py), so I would hope that CMIP5 and CMIP6 (and perhaps even [cesm.py](https://github.com/NCAR/intake-esm/blob/master/intake_esm/cesm.py)) can be handled by the same code. This might entail pushing things like `required_columns` into the configuration file. We could also do better separating the code generating a list of data resource from the code parsing it.

**Comment by naomi-henderson** [comment]
I agree @matt-long .  Having looked more carefully, it doesn't seem worthwhile to write separate code for CMIP6 at least.  The CMIP6 directory structure (at least for now) is much more regular and it is possible to generate the dataframe by just walking down the directory and doing a little checking for required columns and duplicates before saving as csv - all easily done.

**Comment by andersy005** [comment]
@naomi-henderson, I wanted to let you know that I am currently working on this in #46. Feel to free to chime in. I will post an update once #45 is merged.

**Comment by andersy005** [comment]
Addressed in #45, and #46
