### ISSUE TITLE
Adapt for other centers and experiments

### ISSUE THREAD

**Issue by aaronspring** [NCAR/intake-esm#51]
I really like the intake features in combination with xarray. I wonder how your package could be applied on a different supercomputer. 

I'm from MPI-M, Germany and would like to use intake-esm, collections, ... to load our large ensembles.

Do you see a way how intake-esm could be used at a different supercomputer? I think I get the rough concept, but its very complicated and seems to me very much tailored to the NCAR facilities.

But maybe a minimal working example would already be enough to understand the concept in order to adapt it to a new experiment. Right now I dont even know where to start...

**Comment by martindurant** [comment]
I hope NCAR can be helpful for explaining things to you, @aaronspring , and they probably understand your use case better than I do; but still feel free to raise issues on Intake if you find bugs or unclear situations.

**Comment by matt-long** [comment]
@aaronspring thanks for your interest in intake-esm. There is no inherent dependency on being on the NCAR machine, so you should be able to get this working at MPI. It will take a bit of effort, but we are happy to help and I think this would be useful exercise to help iron out some shortcomings in generality. 

I think it's important to distinguish between *building* catalogs and *using* catalogs. The build process yields a database that includes files locations and their attributes (as a `pandas` dataframe). intake-esm builds catalogs by crawling directories and identifying files according to a filename-pattern match (for CESM) or the directory structure (CMIP). The database could be generated by other means too, for instance by connecting to a run database and filling the necessary fields.

You can look at
https://github.com/NCAR/intake-esm/blob/master/tests/cesm1-le_collection-input.yml

which provides an example input file used for building a catalog of the CESM1 Large Ensemble. You'll note that the `locations` fields specify paths; in the case of CESM, these locations are examined to find files that include the "case" string for each ensemble member. Logic in the code enables identifying the files, also relying on information in [config.yaml](https://github.com/NCAR/intake-esm/blob/master/intake_esm/config.yaml) where the types of collections we support are defined. 

In order to support your use case, I think we need to understand whether your data fits into our paradigm in a general sense. For instance, for CESM, we identify files by matching patterns that look like this:
> {casename}.{data_stream}.{variable}.{date_string}.nc

What do you think?

**Comment by aaronspring** [comment]
hi guys,
thanks for the effort.

All files follow this structure:
    MPI-GE/rcp85/rcp850001/outdata/mpiom/rcp850001_mpiom_data_3d_mm_20090101_20091231.nc
- {casename} _ {data_stream} _ {date_string}.nc
- `mpiom` is our `pop`
- all cases have biogeochemistry

However, all variables from a datastream are in the same file. Therefore concatinating these takes ages. So far we mostly use `cdo` for postprocessesing. 

I adapted config.yaml and created a new mpi-ge collection. tried to create a PR to compare but doesnt work.
```
remote: Permission to NCAR/intake-esm.git denied to aaronspring.
fatal: unable to access 'https://github.com/NCAR/intake-esm/': The requested URL returned error: 403
```

**Comment by martindurant** [comment]
> tried to create a PR to compare

You probably want to fork the repo to your account, push changes there and create the PR from that branch.

**Comment by matt-long** [comment]
@aaronspring, yes please create a fork and submit a PR from there. 
I think further changes in the code will be required; we can help with that.

For testing and development purposes, it might be helpful to create a file list. Perhaps as follows.
```bash
find MPI-GE/rcp85/rcp850001/outdata -name "*.nc" > mpi_filelist.txt
```
We can build collections from such files, removing the need to actually be on the machine of interest to test and develop ([an example](https://github.com/NCAR/intake-esm/blob/0165a350ddb38b917286798af636a617c4ec2275/tests/collection_input_test.yml#L8)).

cc @andersy005
