### ISSUE TITLE
trouble when multiple netcdf files in same subdirectory

### ISSUE THREAD

**Issue by naomi-henderson** [NCAR/intake-esm#54]
When there are multiple netcdf files in same subdirectory - only one shows up in the collection dataframe

- For example, in `cmip.py` in the `CMIP6Collection` class definition (but this is not unique to CMIP6), the `entry` dictionary is being overwritten for each new file, see the simple example below.

- I am using:
intake                    0.4.3+25.g3473bf3.dirty          pypi_0    pypi
intake-esm           2019.2.28+113.g0165a35         pypi_0    pypi

- Here is a simple example, and a possible fix
          [intake_esm_example.pdf](https://github.com/NCAR/intake-esm/files/3118361/intake_esm_example.pdf)

**Comment by andersy005** [comment]
Thank you for putting this together, @naomi-henderson. Let me know if you have time to put together a pull request to fix this. Otherwise, I'll handle it for you.

**Comment by naomi-henderson** [comment]
@andersy005 , I am not sure where all this bug appears - it certainly also appears in the `cmip.py CMIP5Collection` and probably in the `cesm.py CESMCollection`, so it would be great if you could do the pull request since you know the code better and are certainly better with python. If it were just in the CMIP6 part, I would have made an attempt. Next time. Thanks!

**Comment by andersy005** [comment]
@naomi-henderson, I tracked the bug down to two locations in cmip.py and patched it in #55. Thank you for providing the fix!

**Comment by naomi-henderson** [comment]
@andersy005 Great, thanks!  Are we sure that the CESM code doesn't suffer from the same problem?
```
       for f in filelist:
            fileparts = self._get_filename_parts(os.path.basename(f), self.component_streams)

            if fileparts is None or len(fileparts) == 0:
                continue

            entries['resource'].append(resource_key)
            entries['resource_type'].append(resource_type)
            entries['direct_access'].append(direct_access)

            entries['case'].append(fileparts['case'])
            entries['component'].append(fileparts['component'])
            entries['stream'].append(fileparts['stream'])
            entries['variable'].append(fileparts['variable'])
            entries['date_range'].append(fileparts['datestr'])

            entries['file_basename'].append(os.path.basename(f))
            entries['file_dirname'].append(os.path.dirname(f) + '/')
            entries['file_fullpath'].append(f)
```

**Comment by andersy005** [comment]
As far as I can tell, 
1) CESM is not affected by this bug because the CESM collection is built in a slight different way -- a directory doesn't play any role in how file attributes/metadata are parsed (all attributes/metadata are parsed from the filename only)--.

2) By looking at the code snippet above, you will notice that the `entries` dictionary is being updated in a different way too. The values in this dictionary are lists:

```python
{'resource': [],
 'resource_type': [],
 'direct_access': [],
 'case': [],
 'component': [],
 'stream': [],
 'variable': [],
 'date_range': [],
 'file_basename': [],
 'file_dirname': [],
 'file_fullpath': []}
```
As a result, during the iteration, we are appending to the lists instead of mutating the values of dictionary values, whereas for CMIP5, and CMIP6 the values in `entry` dictionary are just single value entries that get mutated during iteration. 

I am going to look into this to make sure though.
