### ISSUE TITLE
Extending intake-esm to RDA holdings: add support for ERA5 Reanalysis

### ISSUE THREAD

**Issue by andersy005** [NCAR/intake-esm#66]
https://rda.ucar.edu/datasets/ds630.0/

Resources/Documentation:
 - https://confluence.ecmwf.int/pages/viewpage.action?pageId=85402030#ERA5terminology:analysisandforecast;timeandsteps;instantaneousandaccumulatedandmeanratesandmin/maxparameters-Instantaneous,accumulated,meanrateandmin/maxparameters
- https://confluence.ecmwf.int/display/CKB/ERA5+data+documentation#ERA5datadocumentation-Dataorganisationandaccess
- https://apps.ecmwf.int/codes/grib/param-db

**Comment by andersy005** [comment]
Addressed by #68

**Comment by mickaellalande** [comment]
Is ERA5 reanalysis accessible through intake? Is there an example in the documentation of how to access it?

**Comment by wachsylon** [comment]
@andersy005 

I made one for dkrz era5 data which is on our HPC's disk storage. That means, it also only works on Mistral.

```
dkrz_cdp=intake.open_catalog("https://swift.dkrz.de/v1/dkrz_a44962e3ba914c309a7421573a6949a6/intake-esm/dkrz_data-pool_cloudcatalog.yaml")
esm_dkrz_era=dkrz_cdp.dkrz_era5_disk_grb_fromcloud
```
should work.

However, it is based on raw `grb` data and `intake-esm` does not really support `grb`. We would need a default engine [here](https://github.com/intake/intake-esm/blob/40fe3a7808c14af77d96cfc932b9cebaa6beba10/intake_esm/source.py#L18) for grib. The one i use is `cfgrib`. You may say that users can provide that but since there is no `grib_kwargs`, I cannot for example merge `grb` assets with `netcdf` assets. Which is why I say there is no `grb` support in intake-esm.

Best,
Fabi

**Comment by andersy005** [comment]
@wachsylon, I concur. We should expand the specification to allow intake-esm catalogs to contain `grib`: https://github.com/intake/intake-esm/blob/main/docs/source/explanation/esm-collection-spec.md#assets-object

**Comment by andersy005** [comment]
@wachsylon, I opened an issue for this: https://github.com/intake/intake-esm/issues/452
